// apps/admin/src/app/shared/header/header.component.ts
import { Component, inject } from "@angular/core";
import { RouterLink, RouterLinkActive } from "@angular/router";
import { ThemeService } from "../../core/theme.service";

@Component({
  selector: "app-header",
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: "./header.component.html",
})
export class HeaderComponent {
  readonly theme = inject(ThemeService);

  toggleTheme(): void {
    this.theme.toggle();
  }
}

<header class="border-b border-border bg-card">
  <div class="mx-auto flex max-w-7xl items-center justify-between gap-4 p-3 md:p-4">
    <div class="flex items-center gap-6">
      <a routerLink="/dashboard" class="text-lg font-bold text-primary">LeetCode Lab Admin</a>
      <nav class="flex items-center gap-1">
        <a
          routerLink="/dashboard"
          routerLinkActive="bg-primary text-primary-fg"
          [routerLinkActiveOptions]="{ exact: false }"
          class="btn"
        >Dashboard</a>
        <a
          routerLink="/database"
          routerLinkActive="bg-primary text-primary-fg"
          class="btn"
        >Database</a>
      </nav>
    </div>
    <button
      type="button"
      class="btn"
      (click)="toggleTheme()"
      [attr.aria-label]="theme.isDark() ? 'Chuyển sang sáng' : 'Chuyển sang tối'"
      [title]="theme.isDark() ? 'Sáng' : 'Tối'"
    >
      <span aria-hidden="true">{{ theme.isDark() ? '☀️' : '🌙' }}</span>
      <span class="hidden sm:inline">{{ theme.isDark() ? 'Light' : 'Dark' }}</span>
    </button>
  </div>
</header>

// apps/web/src/components/Header.tsx
import { Link } from "react-router-dom";
import { useTheme } from "../lib/theme.js";

export function Header({ sidebarOpen, onToggleSidebar }: { sidebarOpen: boolean; onToggleSidebar: () => void }) {
  const { theme, toggle } = useTheme();
  return (
    <header className="sticky top-0 z-40 flex h-14 shrink-0 items-center justify-between border-b border-border bg-header-bg px-3 backdrop-blur-md">
      <div className="flex items-center gap-1">
        <button
          type="button"
          onClick={onToggleSidebar}
          aria-label={sidebarOpen ? "Ẩn sidebar" : "Hiện sidebar"}
          className="flex h-9 w-9 items-center justify-center rounded-lg text-text-secondary transition-colors hover:bg-bg-hover hover:text-text-primary"
        >
          <span className="text-lg">{sidebarOpen ? "◁" : "▷"}</span>
        </button>
        <Link to="/" className="flex items-center gap-2 font-semibold text-text-primary no-underline">
          <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-accent text-sm font-bold text-white">
            LC
          </span>
          <span className="hidden text-sm sm:inline">LeetCode Lab</span>
        </Link>
      </div>

      <nav className="flex items-center gap-1 text-sm">
        <a
          href="https://leetcode.com/problems"
          target="_blank"
          rel="noreferrer"
          className="rounded-lg px-3 py-1.5 font-medium text-text-secondary no-underline transition-colors hover:bg-bg-hover hover:text-text-primary"
        >
          LeetCode ↗
        </a>
      </nav>

      <button
        type="button"
        onClick={toggle}
        aria-label="Đổi theme"
        className="flex h-9 w-9 items-center justify-center rounded-lg text-lg text-text-secondary transition-colors hover:bg-bg-hover hover:text-text-primary"
      >
        {theme === "light" ? "🌙" : "☀️"}
      </button>
    </header>
  );
}
